[package]
name = "stochastic_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.4"
log = "^0.4.14"
prettytable-rs = "^0.8"
